### ISSUE TITLE
Crash counts mismatch between CARTO & SODA

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-etl-script#12]
Dan has put together a spreadsheet investigating the crash counts from Socarata and from CARTO, and come up with some figures indicating that in many cases the injury count in CARTO (and CrashMapper) is higher than indicated by the Socrata systems.

https://docs.google.com/spreadsheets/d/14JNTMS4gRszWSVXY0kOGXkYCWWp440Las_PE40nAAT0/edit#gid=248679534

Notably the bottom which lists the most-incorrect months.

```
Year	Month	Injured_NYC	Injured_CARTO	Killed_NYC	Killed_CARTO
2017	2	3907		4061		13		13				CARTO extra 100 injuries
2016	12	4884		5580		24		26				CARTO extra 700 injuries
2016	8	5509		11318		29		27				CARTO nearly 2X the injuries
```

**Comment by gregallensworth** [comment]
#### Exporting from CARTO

Use a query like this, then export as CSV:
```
SELECT
socrata_id,
date_val::date,
number_of_persons_injured,
number_of_cyclist_injured,
number_of_motorist_injured,
number_of_pedestrian_injured,
number_of_persons_killed,
number_of_cyclist_killed,
number_of_motorist_killed,
number_of_pedestrian_killed
FROM crashes_all_prod
WHERE
borough='Brooklyn'
AND socrata_id IS NOT NULL
AND date_val::date >= '2017-02-01' AND date_val::date <= '2017-02-28'
ORDER BY socrata_id
```

#### Exporting from SODA

Use an URL such as this

```
https://data.cityofnewyork.us/resource/qiz3-axqb.csv?$where=date%3E=%272017-02-01%27%20AND%20date%3C%272017-03-01%27&$order=unique_key%20ASC&$limit=50000
```

#### Postprocessing

The two CSVs were saved as XLSX worksheets, then the fields resequenced so the two spreadsheets could be compared side by side.

[SODA-201702-Brooklyn.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1733208/SODA-201702-Brooklyn.xlsx)
[CARTO-201702-Brooklyn.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1733209/CARTO-201702-Brooklyn.xlsx)


#### Methods

The records are sorted by the `unique_key` aka `socrata_id` field, so we can scroll through the two sheets in tandem and look for crashes present in CARTO but not in SODA, and present in SODA but not in CARTO.

**Comment by gregallensworth** [comment]
#### Methods and Overview

The records are sorted by the `unique_key` aka `socrata_id` field, so we can scroll through the two sheets in tandem and look for crashes present in CARTO but not in SODA, and present in SODA but not in CARTO.

General stats for Brooklyn 201702, and Brooklyn 20170201:

```
SODA		3124 crash records			Feb 1 = 114 crash records
CARTO		4453 crash records			Feb 1 = 148 crash records
```

I then used Excel's filter capability on *both sheets* to filter by the "Total Inj" field being not-0, and began "just perusing" the data. It is immediately clear that many records are present in the CARTO output but not the SODA output.

Rows which are *present in CARTO but not SODA* in the first 315 rows alone:

```
socrata_id	date	Total Inj	Total Kil	C Inj	C Kil	M Inj	M Kil	P Inj	P Kil
3608204		2/2/2017	3	0	0	0	6	0	0	0
3608211		2/1/2017	1	0	2	0	0	0	0	0
3608292		2/1/2017	1	0	0	0	2	0	0	0
3608302		2/1/2017	1	0	0	0	2	0	0	0
3608326		2/1/2017	1	0	0	0	2	0	0	0
3608653		2/2/2017	1	0	0	0	1	0	0	0
3608701		2/2/2017	1	0	0	0	1	0	0	0
3608944		2/2/2017	1	0	0	0	0	0	1	0
3608973		2/1/2017	1	0	1	0	0	0	0	0
3609022		2/1/2017	1	0	0	0	0	0	1	0
3609434		2/4/2017	1	0	0	0	1	0	0	0
3609438		2/2/2017	1	0	0	0	1	0	0	0
3609462		2/4/2017	1	0	0	0	1	0	0	0
3609633		2/4/2017	1	0	0	0	0	0	1	0
3609645		2/4/2017	2	0	0	0	2	0	0	0
3609716		2/4/2017	1	0	0	0	1	0	0	0
3609825		2/4/2017	1	0	0	0	1	0	0	0
3609845		2/3/2017	1	0	0	0	0	0	1	0
3610001		2/3/2017	1	0	0	0	1	0	0	0
```

This initial sampling indicates SODA 22 "missing" injuries which are present in CARTO, in the first 315 lines (10%) of the file.

*Are we seeing a condition in which records have vanished from SODA?*

I have noted previously during January 2018, that at least 3 records had *had their date changed* from 2017 to 2018, one year **after** these records had been loaded into CARTO. That is, it is not possible that a January 2017 crash record had its date misinterpreted; the record `cartodb_id` numbers clearly indicate that this record had been in place for some time, loaded alongside other records which still read Jan 2017.

Perhaps the data over at SODA are subject to later editing and human error?

Let's start by investigating this initial set of 20 "missing" crashes in SODA, and see what's there.

**Comment by gregallensworth** [comment]
**Quick Stats** comparison for **201702**

*NOTE* that my counts here are not aggregating by borough, nor at this time filtering by borough being non-blank. As such, these sums will differ from the borough-aggregates listed in Dan's worksheet.

```
CARTO 201702.xlsx = 16646 crash records, 4109 total injuries (Persons Injured field)
SODA 201702.xlsx = 15701 crash records, 3907 total injuries (Persons Injured field)

Diff: CARTO has 945 more crashes (6% more) and 202 more injuries (5% more)
```

**Comment by gregallensworth** [comment]
Attached below is a script I wrote to compare the crash lists, and its output.

The CARTO listing for 2017-02 has 398 duplicated crashes, adding up to 85 injuries and 0 fatalities.

The CARTO listing contains 569 crashes which are not present in SODA, adding up to 139 injuries and 0 fatalities.

The noted variance is 202 injuries and 945 crashes. The variances seen above would account for 967 crashes, 224 injuries, and 0 fatalities. NOTE that the exact variance accounting here may not add up exactly, as some duplicates may be present in SODA or absent from SODA and a deeper analysis was not done there. Relevant point is that the 5% error we're seeing, is about 90% accounted by these two sources noted above.


[Crashes_MissingFromSODA.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1737841/Crashes_MissingFromSODA.xlsx)
[DuplicateCrashesInCARTO.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1737842/DuplicateCrashesInCARTO.xlsx)
[compare_crash_lists.py.txt](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1737843/compare_crash_lists.py.txt)
[Crashes_MissingFromCARTO.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1737844/Crashes_MissingFromCARTO.xlsx)

**Comment by danrademacher** [comment]
Seems like a process to dedupe the content in CARTO would be reasonable. Even if that’s only a partial resolution, not counting things twice or more is just a good idea

**Comment by gregallensworth** [comment]
Per issue #9 the duplicated *socrata_id* records were visually examined and one record from each pair was deleted. This should significantly improve the variance for 2017-02, which was the second-most-variant month noted.

**Comment by gregallensworth** [comment]
Virtually all of the variance in 2016-02 was explained and solved by the duplicate records. However, those duplicates were dated entirely within 2017-02-26, so are not causes of variance elsewhere. Others months need separate investigation.

### New month: 2016-12

Export files were generated for `date >= 2016-12-01 AND date < 2017-01-01` and are attached,. Quick stats are:
```
CARTO: 19235 crashes, 4884 injuries, 24 fatalities
SODA: 19236 crashes, 4885 injuries, 24 fatalities
```

**The difference here is 1 single crash (with 1 single injury)** present in SODA but not in CARTO, likely due to the usual "backlogged too late" effect otherwise noted.

*In this case, I suggest that the variance noted in Dan's analysis, is due to a flaw in methodology.* For example the Socrata Data API being used by the ETL may not be the same as the pre-digested spreadsheets which Dan was using, or aggregation by borough may not have been done accurately. (the ETL uses polygon containment, which gets a lot more hits than SODA's own field)

**Comment by gregallensworth** [comment]
### Most Variant Month: 2016-08

The most-variant month listed in Dan's analysis is 2016-08, with CARTO showing **95% more injuries** than derived from the Socrata-provided spreadsheets. Export files were generated from SODA and CARTO, and are attached. Quick stats are:

```
CARTO: 19690 crashes, 5510 injuries, 28 fatalities
SODA: 19690 crashes, 5509 injuries, 29 fatalities
```

**This is a variation of 1 injury and 1 fatality, out of the agreed-upon 19690 crash records.** This would be considered well within acceptable variances.

Again, I suspect that the CSV export tool being used is very different than the SODA which is used for ETL, and/or the aggregation methodology being used is different.

**Comment by danrademacher** [comment]
hmm, but in the app:
![image](https://user-images.githubusercontent.com/1423200/36618113-bf889b3a-189e-11e8-877f-7b9dcff75adb.png)

http://vis.crashmapper.org/?cfat=true&cinj=true&geo=city_council&mfat=true&minj=true&p1end=2018-02&p1start=2017-02&p2end=2016-09&p2start=2015-09&pfat=true&pinj=true&primary&reference=citywide&view=trend

**Comment by danrademacher** [comment]
```
{
"total_crashes": 19691,
"cyclist_injured": 1234,
"cyclist_killed": 3,
"motorist_injured": 8467,
"motorist_killed": 7,
"pedestrian_injured": 1617,
"pedestrian_killed": 17,
"persons_injured": 11318,
"persons_killed": 27,
"year_month": "2016-08"
},
```

query:
https://chekpeds.carto.com/api/v2/sql?q=SELECT+COUNT(c.cartodb_id)+as+total_crashes,+SUM(c.number_of_cyclist_injured)+as+cyclist_injured,+SUM(c.number_of_cyclist_killed)+as+cyclist_killed,+SUM(c.number_of_motorist_injured)+as+motorist_injured,+SUM(c.number_of_motorist_killed)+as+motorist_killed,+SUM(c.number_of_pedestrian_injured)+as+pedestrian_injured,+SUM(c.number_of_pedestrian_killed)+as+pedestrian_killed,+SUM(c.number_of_pedestrian_injured+%2B+c.number_of_cyclist_injured+%2B+c.number_of_motorist_injured)+as+persons_injured,+SUM(c.number_of_pedestrian_killed+%2B+c.number_of_cyclist_killed+%2B+c.number_of_motorist_killed)+as+persons_killed,+year+%7C%7C+%27-%27+%7C%7C+LPAD(month::text,+2,+%270%27)+as+year_month+FROM+crashes_all_prod+c+GROUP+BY+year,+month+ORDER+BY+year+asc,+month+asc

**Comment by danrademacher** [comment]
The above two comments suggest that the spikes I was seeing in my analysis is present **in the application** but not **in the data**.

I'm puzzled for sure.

**Comment by danrademacher** [comment]
Another round of checking using queries in (this sheet)[https://docs.google.com/spreadsheets/d/14JNTMS4gRszWSVXY0kOGXkYCWWp440Las_PE40nAAT0/edit#gid=248679534&range=A41] suggests that the root of the problem is that the subtotals for `pedestrians_injured`,`cyclists_injured`, and `motorists_injured` in CARTO are not correct, even though `persons_injured` is very close. 

Mode | Injured_NYC_sum | Injured_CARTO_sum
-- | -- | --
pedestrian | 883 |  1571
cyclist | 678 | 1176
motorist | 4244 | 8201

Based on un-aggregated crash data pulled with [this query](https://chekpeds.carto.com/api/v2/sql?format=csv&q=SELECT+month,year,date_val,crash_count,number_of_persons_injured,number_of_pedestrian_injured,number_of_cyclist_injured,number_of_motorist_injured,number_of_persons_killed,number_of_pedestrian_killed,number_of_cyclist_killed,number_of_motorist_killed,borough,city_council,community_board,neighborhood,nypd_precinct+FROM+crashes_all_prod+where+date_val+between+'2016-08-01'+and+'2016-08-31'+order+by+date_val+asc)

Compared to crash export from https://data.cityofnewyork.us/Public-Safety/2016-08/rt6i-7uc9/data.

Here's what [the map](http://crashmapper.org/#/?cfat=true&cinj=true&endDate=2016-08&geo=citywide&identifier=&lngLats=%255B%255D&mfat=true&minj=true&noInjFat=false&pfat=true&pinj=true&startDate=2016-08) app shows:
![image](https://user-images.githubusercontent.com/1423200/36654267-3a51f334-1a70-11e8-8f17-51ceeed4f0fd.png)

I wonder if the best approach here would be to simply blow away and reimport the three most problematic months rather than trying to divine what went wrong when they were imported.

The most variant months are:

Year | Month
-- | --
2016 | 8
2016 | 9
2017 | 1

**Comment by gregallensworth** [comment]
I agree with Dan that "`pedestrians_injured, cyclists_injured, and motorists_injured` in CARTO are not correct, even though `persons_injured` is very close" My analyses above were solely with the `persons_injured` field and not the sum of the three subtypes of injured party.

This step, is to examine both the SODA and CARTO data for **2016-08** to determine the difference between the `persons_injured` field and the sum of the 3 injury fields (motorist, pedestrian, cyclist) to determine the nature of this mismatch.

If the data are badly mismatched in SODA, then reloading would achieve nothing except reloading records with the same bad math (in which 1 motorist + 2 bicyclists + 0 peds = 5 persons). But if the SODA data are nicely matched with acceptable internal variance, then perhaps reloading could make sense.

[SODA-injurycrashes-201608.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1759838/SODA-injurycrashes-201608.xlsx)
[CARTO-injurycrashes-201608.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1759839/CARTO-injurycrashes-201608.xlsx)
[data-fetch-methodology.txt](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1759840/data-fetch-methodology.txt)

Results thus far:
* CARTO data does show a huge internal variance between the sum of `persons_injured` and the sum of the 3 injury subtypes (11318 to 5510).
* However, SODA data shows only a 5% internal variance (5809 to 5509).

SODA largest single-crash variances:
```
1 instance of 1 injury but 4 motorist (diff = 3)
1 instance of 9 injuries but 7 motorist (diff = 2)
Large majority are 0 diff or +1 to -1 diff.
```

CARTO internal variances:
```
Few records have an internal variance of 0, most are +1 but +_16 +18 +21 are noted
```

Some specifics:
```
3492924     SODA 5 motorist = 5 total, in CARTO as 15 motorist = 5 total
3492692     SODA 3 motorist = 3 total, in CARTO as 6 motorist = 3 total
3492614     SODA 2 motorists = 1 total (internal variance), in CARTO as 3 motorist (did they sum 2+1?)
3498009     SODA 7 motorists = 7 total, in CARTO as 28 motorist = 7 total
```

Summary:

* Something may have been significantly borked in the ETL script back then, in regards to loading the by-vehicle injury counts, and specifically the motorist injury counts. Reloading the data will be a real bear, at 4000 crashes per month, so I will need to do some creative invention trying to make that happen.
* Other months are likely exhibit this same sort of variance, not only the 3 described at https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/issues/12#issuecomment-368392100 and should be examined for these sort of issues.

**Comment by gregallensworth** [comment]
#### 2017-02

The goal here is to determine whether the variances noted in 2016-08 above are similar to those affecting other months, e.g. 2017-02.

[SODA-injurycrashes-201702.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1760025/SODA-injurycrashes-201702.xlsx)
[CARTO-injurycrashes-201702.xlsx](https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/files/1760026/CARTO-injurycrashes-201702.xlsx)


*CARTO dataset, internal variances overview*

Total variance:
```
3976 summed versus 3886 persons injured = 90 = 3.1%
```

Most variances are +1 to -1

Most extreme variances within CARTO:
```
3610697     CARTO 0 specified = 6 total; SAME as in in SODA
3607913     SODA 4 motorist = 4 total, in CARTO 8 motorist = 4 total
3608213     SODA 4 motorist = 4 total, in CARTO 8 motorist = 4 total
3608375     SODA 6 motorist = 6 total, in CARTO 12 motorist = 6 total
```

*SODA dataset, internal variances overview*

Total variance:
```
3965 summed versus 3909 injured = -56 = 1.4%

```

Most variances -1 (sum 1 higher than injured persons)

Most extreme variances in SODA:
```
3610697     0 specified = 6 total
3619210     2 motorist = 0 total
```

*Summary*

Again, the per-vehicle injury subcounts are loaded incorrectly, particularly the motorist field. Unlike 2016-08 the grand total variances are smaller overall, but the same phenomenon is present.

**Comment by gregallensworth** [comment]
#### Q4 2017

The next question of the ETL bugs noted above, is whether this issue is ongoing, or previously solved. This affects whether we may just patch the existing data, or must alter the ETL script to fix a longer-standing issue.

In CARTO a query was done over the 3-month period of Q4 2017, to show the most extreme internal variances. If the ETL issues have been corrected, then only several variances should exist and in the range of +1 and -1, with -18 (a 6 becoming 24) not happening.

```
SELECT
    socrata_id,
    date_val,
    sum_of_persons_injured,
    number_of_persons_injured,
    ABS(sum_of_persons_injured - number_of_persons_injured) AS variance
FROM (
    SELECT
        socrata_id,
        date_val::date,
        number_of_persons_injured,
        number_of_cyclist_injured + number_of_motorist_injured + number_of_pedestrian_injured AS sum_of_persons_injured,
        number_of_cyclist_injured,
        number_of_motorist_injured,
        number_of_pedestrian_injured
    FROM crashes_all_prod
    WHERE
    socrata_id IS NOT NULL
    AND date_val::date >= '2017-10-01' AND date_val::date < '2017-12-01'
    ORDER BY socrata_id
) monthcrashes
WHERE sum_of_persons_injured > 0 OR number_of_persons_injured > 0
ORDER BY variance DESC
```


*Within Q4 2017, only 8 non-0 variances were found* which is a great improvement compared to these months previously investigated. And, all of these variances *are confirmed to also be present in SODA output.* indicating that the ETL is doing what it should with the data given.

```
3801293         3 VS 1 total    confirmed in SODA
3767170         6 VS 3 total    confirmed in SODA
3761686         6 VS 4 total    confirmed in SODA
3767863         2 VS 0 total    confirmed in SODA
3777714         0 VS 1 total    confirmed in SODA
3794374         2 VS 1 total    confirmed in SODA
3790959         0 VS 1 total    confirmed in SODA
3764710         1 VS 0 total    confirmed in SODA
```

Going back as far as March 2017, the data all look fine. It is February and January 2017 which start to exhibit wider internal variances, and going further back this appears consistent enough to warrant addressing the issue *prior to 2017-06*.

Next course of action, to correct it. Create a script to:
* load CARTO records and SODA records from 2015-01-01 through 2017-03-31
* Compare for variances (a large majority have 0 injuries and that's a lot of UPDATE queries we wouldn't need to run) to generate a list of diffs,
* then update records in the CARTO table by *socrata_id*

**Comment by gregallensworth** [comment]
Much better.

![image](https://user-images.githubusercontent.com/3117633/36808581-5d8c0ec8-1c7a-11e8-8ae9-b2865c5315e7.png)

**Comment by gregallensworth** [comment]
#### Doing it over, eye on fatalities

Dan did some analyses and seems to be seeing variances in fatality counts, which weren't the focus of the prior updates.  Specifically, *the date range of 2017-03 through 2017-12* seems to be tallying up crashes properly and injuries properly, but it showing lower fatality counts than would be expected from the SODA data.

As before, SODA is showing some small internal variances between the persons killed field (TOTAL below) and the sum of peds, motorists, & cyclists killed (KSUM below). The CARTO and SODA tallies are given below.

```
MONTH     TOTAL  KSUM     CARTO
2017-03    17      17        12
2017-04    23      23        17
2017-05    12      12        10
2017-06    21      21        16
2017-07    32      32        23
2017-08    22      23        14
2017-09    26      26        20
2017-10    25      27        17
2017-11    24      25        16
2017-12    16      16        13
```

**Comment by gregallensworth** [comment]
#### Fatality counts: Specific crash-by-crash comparisons

**201703**

SODA shows 5 crashes with 1 fatality apiece, accounting for the variance of 17 fatalities (SODA) vs 5 (CARTO).

```
             SODA      CARTO
3624204      2i/1f     3i/0f   1 injury-to-fatality conversion
3626043      0i/1f     1i/0f   1 injury-to-fatality conversion
3628393      0i/1f     1i/0f   1 injury-to-fatality conversion
3630562      0i/1f     1i/0f   1 injury-to-fatality conversion
3635027      0i/1f     1i/0f   1 injury-to-fatality conversion
```

**Comment by danrademacher** [comment]
Hmm, here's an interesting discovery: https://dev.socrata.com/docs/system-fields.html

SODA has **hidden system fields**! Including `updated_at`, which allow queries like this:
https://data.cityofnewyork.us/resource/qiz3-axqb.json?$where=:updated_at > '2018-01-20'

But they also include this caution:
>Data providers use many different methods to update datasets. In some cases, they use tools like DataSync or the Publisher API to update datasets, and we can tell which records within the dataset have actually been modified, and only update them accordingly. **When data providers perform a full replace of the dataset using the Publisher API, all of its records will be updated within short period of time, in which case a query based on :updated_at will show that all of the records have changed.**

If NYC's `updated_at` dates are reasonable, this might be a much better approach to data syncing.

They also have `created_at`, which I admit is a bit kerflummoxing if it works, since it means all this messing about with crash dates was a red herring. OTOH, if these previously unknown fields solved our problems, then that would be a fine thing.

**Comment by gregallensworth** [comment]
A quick checkup on the injury-to-fatality conversions. This hypothesis is further corroborated upon examination of the *update_at* field, indicating that the record was indeed modified **over 3 months after the fact**.

```
Crash # 3649309
Date: 2017-02-03

Logged as 6 injury & 0 fatality
Now reads 5 injury & 1 fatality

Updated At: 2017-05-11
```

This effectively confirms the "conversion" theory as to the cause of the minor injury variances and major fatality variances. It also gives an idea of the minimum timeframe to consider when looking back for retroactive updates: 3 to 4 months.

**Comment by gregallensworth** [comment]
I have opened issue #13 to discuss the possibility of a new ETL job or offline task, to rectify altered records.

I have reopened #6 to discuss that the "one month window" may be insufficient to catch all new crashes.

**Comment by danrademacher** [comment]
and I verified:
![image](https://user-images.githubusercontent.com/1423200/36992138-dca1debc-205e-11e8-9aff-f78f05ccc897.png)

https://docs.google.com/spreadsheets/d/1Xxe4FlnbOMOTlC3iAdZz4oliEX0a9Scu0X8JJ49Pbpc/edit#gid=248679534
