### ISSUE TITLE
Update requirements and README for local running with sendgrid

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-etl-script#26]
In the README, we say that given a `.env` file, we can run `main.py` locally like this:

> Install Python requirements:
> 
> ```
> pip install -r requirements.txt
> ```
>  
> ## Running Locally
> 
> Run the script using Python 2.7 by doing:
> 
> ```
> python main.py
> ```

I have done that successfully in the past. But now, it fails on :
```bash
  File "main.py", line 15, in <module>
    from sendgrid import SendGridAPIClient
ImportError: No module named sendgrid
```

That's after a fresh run on pip install. I also tried adding `sendgrid` to `requirements.txt` and running again, same error.

Can you update the README, requirements.txt or anything else we need to get local running working again on a fresh install of this repo?

**Comment by danrademacher** [comment]
Fir example, I see new config vars in Heroku, but those are not reflected in README
![image](https://user-images.githubusercontent.com/1423200/76127975-fd353d00-5fb7-11ea-9fac-139165afa667.png)

**Comment by danrademacher** [comment]
wait, I missed one:
![image](https://user-images.githubusercontent.com/1423200/76128110-438a9c00-5fb8-11ea-8817-c83c8474c8a8.png)

**Comment by danrademacher** [comment]
Added those to my local `/env' and unsurprisingly got the same error:
![image](https://user-images.githubusercontent.com/1423200/76128305-cc093c80-5fb8-11ea-8e9c-c679d15c2edc.png)

I imagine we must need to add something to `requirements.txt` that actually installs `sendgrid` -- though even better would be a way to ignore `sendgrid` when one is running manually from CLI, since we do that mostly when the thing is broken and we already know it.

**Comment by fahadkirmani** [comment]
Yes I have pushed the changes for sendgrid in requirements.txt and README.txt
Now it will work fine on you local environment.

**Comment by fahadkirmani** [comment]
Hi Dan,

I did the change in requirements.txt and README file and pushed the changes
into the git.  Sorry for not doing those change before as unaware of it.
If Christine or you can create an email group then I can forward the error
email to that group.
I am surprised why error notification did not worked in production
environment as I have tested it properly and it worked fine on my end.

I think for now we are facing rate limit issues for now with the script and
need to revamp the script.
Here are my suggestion for it.
1-Convert the code to python3
2-use panda library for it
https://dev.socrata.com/foundry/data.cityofnewyork.us/h9gi-nx95

As it will help us for pagination and other stuff to reconcile data with
our system.
3-Do error, success and reports notification using slack channel so we will
be up to date on daily basis about ETL process.

Let me know what you think.

Kind regards
Fahad

**Comment by danrademacher** [comment]
Hmm. I just pulled the latest and reran `pip install` but got same results:

```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from sendgrid import SendGridAPIClient
ImportError: No module named sendgrid
```

Upgrading to Python 3 seems wise, but shouldn't be required to solve this urgent data gap issue. As for Pandas, I don't see how that would help us since pagination on the SODA side is not our issue. Having too much on the CARTO side is. Probably we need to more fully refactor the CARTO importer to use the BATCH API, but that would be under #25 

Tomorrow, I'll have @gregallensworth on my team try to run the import script locally to see if he has any better luck.

**Comment by danrademacher** [comment]
Actually, confirmed I can run this locally again. I forgot to `export` the new env variables after rerunning the install
