### ISSUE TITLE
Past records not in any assembly district

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/nyc-crash-mapper-etl-script#39]
Discovered while updating polygon data in #38 

The `crashes_all_prod` table has 2,071,732 crashes in it today, of which 205,560 (about 10%) have NULL for `assembly`

That's about 10% which "feels" like a lot to fall outside of any assembly district but (presumably) fitting into the five boroughs.

I should check into this,
- see how this many fall outside any Assembly District
- and see to what degree this also means City Council, Neighborhood, Community Board, ...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1109423802232195/1203963804851996)

**Comment by gregallensworth** [comment]
### Initial overview

I exported a shapefile of the 205,560 crash-points `SELECT * FROM crashes_all_prod WHERE assembly IS NULL`

And I exported the `assembly` as GeoJSON. This is the old 2015 shapes, but that fits our intent, finding why the **past** records have been coming up this way.

Initial impressions are that this is indeed an edge effect. But many of them seem as if they would not be solved with a simple buffer.
- Many are on bridges which are not covered by these polygons. Those may require desktop GIS work to find the closest district and assign them.
- Many are "simply" edge effects where a combination of bad coordinates + districts differing from streets data add up to put a crash a few meters outside of any area. Some are 20+ meters outside of an area.
- A few are well outside of any Assembly district and those seem very odd. Maybe data entry error? Maybe a very tiny island? Maybe a bicyclist hit someone whilst on a ferry?


### Overview

![image](https://user-images.githubusercontent.com/3117633/218596557-4ba75e50-d067-450e-8634-38988deac9f2.png)

### Plain Ol' Edges Example

![image](https://user-images.githubusercontent.com/3117633/218598735-9a46030e-a1df-4c47-9d6a-259c47fd42cc.png)

### Bridges Example

![image](https://user-images.githubusercontent.com/3117633/218598187-2e053438-febd-4604-b566-a97f6aec3259.png)

**Comment by danrademacher** [comment]
Further discussion, if we fixed this by grabbing the unclipped versions, it would open a whole can of worms with other layers:

None of the 7 offered polygons include bridges. For for all 7 it’s similar:

- get unclipped
- load into some new table
- create new field to populate them
- populate by intersection (weeks!)
- rename fields
- rename tables

We don't have budget for this right now. Let me check with client and inform her about this before we close this out as wont-fix

**Comment by danrademacher** [comment]
OK, just chatted with Christine and she agreed with leaving this as is
