### ISSUE TITLE
Repair Walkmapper scripts

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-etl-script#43]
Over in #31 we made some scripts that are apparently not working.

Slack:
>Though the other scheduled task, walkmapper obstructions. has an error relevant to the MySQLdb library having updated god only knows how long ago, Is that even a thing? I recall she had me throw that together one afternoon, and the proposed website where it was to be used wasn't even a real website yet, or some such... Should that scheduled task just be disabled, maybe even the code removed?

I asked Christine if these were really in use or could we shut them off. Her reply:

> Yes we need to fix the scripts.
> the project was delayed many times , but we are poised to launch next week.
> the iOS app is already live . “walkmapper” on your phone.

I wonder if this will require coordination with the developer on the otehr side, which IIRC was a pain point last time.

**Comment by gregallensworth** [comment]
I need more information to proceed: the MySQL database credentials.

The `walkmapper/mysql2carto.py` script fetches records from a MySQL database, then loads them into CARTO.

However, I do not have the complete database credentials for the MySQL server: I have a username and password, but the not the database hostname.

I do wonder whether she is aware of what script this is. If they think they have a data pipeline, and that they are preparing to launch, whereas this script has not worked in a couple of years and given the settings in Heroku (database hostname) it likely never worked. Maybe she can clarify what she thinks this script does: does their current app in fact read from CARTO and expect to be fetching new entries from MySQL? If so, I need those credentials.

```
2024-12-23T20:00:23.177700+00:00 app[scheduler.9608]: 08:00:23 PM - INFO - Found 233 obstructions in CARTO
2024-12-23T20:00:23.254578+00:00 app[scheduler.9608]: 08:00:23 PM - INFO - Found 107 obstructions in MySQL
```

**Comment by gregallensworth** [comment]
Done and deployed. There is just the one script, mysql2carto.py
